import type {
  KanaEntry,
  KanaGroup,
  KanaRowKey,
  KanaScript,
  KanaSelectionKey,
} from "@/lib/types";

type KanaRowDefinition = {
  key: KanaRowKey;
  group: KanaGroup;
  label: string;
  entries: KanaEntry[];
};

type FlatRows = Record<KanaGroup, KanaEntry[]>;

function sliceRow(source: KanaEntry[], start: number, count: number): KanaEntry[] {
  return source.slice(start, start + count);
}

const flatRowsByScript: Record<KanaScript, FlatRows> = {
  hiragana: {
    basic: [
      { kana: "あ", romaji: "a" },
      { kana: "い", romaji: "i" },
      { kana: "う", romaji: "u" },
      { kana: "え", romaji: "e" },
      { kana: "お", romaji: "o" },
      { kana: "か", romaji: "ka" },
      { kana: "き", romaji: "ki" },
      { kana: "く", romaji: "ku" },
      { kana: "け", romaji: "ke" },
      { kana: "こ", romaji: "ko" },
      { kana: "さ", romaji: "sa" },
      { kana: "し", romaji: "shi" },
      { kana: "す", romaji: "su" },
      { kana: "せ", romaji: "se" },
      { kana: "そ", romaji: "so" },
      { kana: "た", romaji: "ta" },
      { kana: "ち", romaji: "chi" },
      { kana: "つ", romaji: "tsu" },
      { kana: "て", romaji: "te" },
      { kana: "と", romaji: "to" },
      { kana: "な", romaji: "na" },
      { kana: "に", romaji: "ni" },
      { kana: "ぬ", romaji: "nu" },
      { kana: "ね", romaji: "ne" },
      { kana: "の", romaji: "no" },
      { kana: "は", romaji: "ha" },
      { kana: "ひ", romaji: "hi" },
      { kana: "ふ", romaji: "fu" },
      { kana: "へ", romaji: "he" },
      { kana: "ほ", romaji: "ho" },
      { kana: "ま", romaji: "ma" },
      { kana: "み", romaji: "mi" },
      { kana: "む", romaji: "mu" },
      { kana: "め", romaji: "me" },
      { kana: "も", romaji: "mo" },
      { kana: "や", romaji: "ya" },
      { kana: "ゆ", romaji: "yu" },
      { kana: "よ", romaji: "yo" },
      { kana: "ら", romaji: "ra" },
      { kana: "り", romaji: "ri" },
      { kana: "る", romaji: "ru" },
      { kana: "れ", romaji: "re" },
      { kana: "ろ", romaji: "ro" },
      { kana: "わ", romaji: "wa" },
      { kana: "を", romaji: "wo" },
      { kana: "ん", romaji: "n" },
    ],
    dakuten: [
      { kana: "が", romaji: "ga" },
      { kana: "ぎ", romaji: "gi" },
      { kana: "ぐ", romaji: "gu" },
      { kana: "げ", romaji: "ge" },
      { kana: "ご", romaji: "go" },
      { kana: "ざ", romaji: "za" },
      { kana: "じ", romaji: "ji" },
      { kana: "ず", romaji: "zu" },
      { kana: "ぜ", romaji: "ze" },
      { kana: "ぞ", romaji: "zo" },
      { kana: "だ", romaji: "da" },
      { kana: "ぢ", romaji: "ji" },
      { kana: "づ", romaji: "zu" },
      { kana: "で", romaji: "de" },
      { kana: "ど", romaji: "do" },
      { kana: "ば", romaji: "ba" },
      { kana: "び", romaji: "bi" },
      { kana: "ぶ", romaji: "bu" },
      { kana: "べ", romaji: "be" },
      { kana: "ぼ", romaji: "bo" },
      { kana: "ぱ", romaji: "pa" },
      { kana: "ぴ", romaji: "pi" },
      { kana: "ぷ", romaji: "pu" },
      { kana: "ぺ", romaji: "pe" },
      { kana: "ぽ", romaji: "po" },
    ],
    combo: [
      { kana: "きゃ", romaji: "kya" },
      { kana: "きゅ", romaji: "kyu" },
      { kana: "きょ", romaji: "kyo" },
      { kana: "しゃ", romaji: "sha" },
      { kana: "しゅ", romaji: "shu" },
      { kana: "しょ", romaji: "sho" },
      { kana: "ちゃ", romaji: "cha" },
      { kana: "ちゅ", romaji: "chu" },
      { kana: "ちょ", romaji: "cho" },
      { kana: "にゃ", romaji: "nya" },
      { kana: "にゅ", romaji: "nyu" },
      { kana: "にょ", romaji: "nyo" },
      { kana: "ひゃ", romaji: "hya" },
      { kana: "ひゅ", romaji: "hyu" },
      { kana: "ひょ", romaji: "hyo" },
      { kana: "みゃ", romaji: "mya" },
      { kana: "みゅ", romaji: "myu" },
      { kana: "みょ", romaji: "myo" },
      { kana: "りゃ", romaji: "rya" },
      { kana: "りゅ", romaji: "ryu" },
      { kana: "りょ", romaji: "ryo" },
      { kana: "ぎゃ", romaji: "gya" },
      { kana: "ぎゅ", romaji: "gyu" },
      { kana: "ぎょ", romaji: "gyo" },
      { kana: "じゃ", romaji: "ja" },
      { kana: "じゅ", romaji: "ju" },
      { kana: "じょ", romaji: "jo" },
      { kana: "びゃ", romaji: "bya" },
      { kana: "びゅ", romaji: "byu" },
      { kana: "びょ", romaji: "byo" },
      { kana: "ぴゃ", romaji: "pya" },
      { kana: "ぴゅ", romaji: "pyu" },
      { kana: "ぴょ", romaji: "pyo" },
    ],
  },
  katakana: {
    basic: [
      { kana: "ア", romaji: "a" },
      { kana: "イ", romaji: "i" },
      { kana: "ウ", romaji: "u" },
      { kana: "エ", romaji: "e" },
      { kana: "オ", romaji: "o" },
      { kana: "カ", romaji: "ka" },
      { kana: "キ", romaji: "ki" },
      { kana: "ク", romaji: "ku" },
      { kana: "ケ", romaji: "ke" },
      { kana: "コ", romaji: "ko" },
      { kana: "サ", romaji: "sa" },
      { kana: "シ", romaji: "shi" },
      { kana: "ス", romaji: "su" },
      { kana: "セ", romaji: "se" },
      { kana: "ソ", romaji: "so" },
      { kana: "タ", romaji: "ta" },
      { kana: "チ", romaji: "chi" },
      { kana: "ツ", romaji: "tsu" },
      { kana: "テ", romaji: "te" },
      { kana: "ト", romaji: "to" },
      { kana: "ナ", romaji: "na" },
      { kana: "ニ", romaji: "ni" },
      { kana: "ヌ", romaji: "nu" },
      { kana: "ネ", romaji: "ne" },
      { kana: "ノ", romaji: "no" },
      { kana: "ハ", romaji: "ha" },
      { kana: "ヒ", romaji: "hi" },
      { kana: "フ", romaji: "fu" },
      { kana: "ヘ", romaji: "he" },
      { kana: "ホ", romaji: "ho" },
      { kana: "マ", romaji: "ma" },
      { kana: "ミ", romaji: "mi" },
      { kana: "ム", romaji: "mu" },
      { kana: "メ", romaji: "me" },
      { kana: "モ", romaji: "mo" },
      { kana: "ヤ", romaji: "ya" },
      { kana: "ユ", romaji: "yu" },
      { kana: "ヨ", romaji: "yo" },
      { kana: "ラ", romaji: "ra" },
      { kana: "リ", romaji: "ri" },
      { kana: "ル", romaji: "ru" },
      { kana: "レ", romaji: "re" },
      { kana: "ロ", romaji: "ro" },
      { kana: "ワ", romaji: "wa" },
      { kana: "ヲ", romaji: "wo" },
      { kana: "ン", romaji: "n" },
    ],
    dakuten: [
      { kana: "ガ", romaji: "ga" },
      { kana: "ギ", romaji: "gi" },
      { kana: "グ", romaji: "gu" },
      { kana: "ゲ", romaji: "ge" },
      { kana: "ゴ", romaji: "go" },
      { kana: "ザ", romaji: "za" },
      { kana: "ジ", romaji: "ji" },
      { kana: "ズ", romaji: "zu" },
      { kana: "ゼ", romaji: "ze" },
      { kana: "ゾ", romaji: "zo" },
      { kana: "ダ", romaji: "da" },
      { kana: "ヂ", romaji: "ji" },
      { kana: "ヅ", romaji: "zu" },
      { kana: "デ", romaji: "de" },
      { kana: "ド", romaji: "do" },
      { kana: "バ", romaji: "ba" },
      { kana: "ビ", romaji: "bi" },
      { kana: "ブ", romaji: "bu" },
      { kana: "ベ", romaji: "be" },
      { kana: "ボ", romaji: "bo" },
      { kana: "パ", romaji: "pa" },
      { kana: "ピ", romaji: "pi" },
      { kana: "プ", romaji: "pu" },
      { kana: "ペ", romaji: "pe" },
      { kana: "ポ", romaji: "po" },
    ],
    combo: [
      { kana: "キャ", romaji: "kya" },
      { kana: "キュ", romaji: "kyu" },
      { kana: "キョ", romaji: "kyo" },
      { kana: "シャ", romaji: "sha" },
      { kana: "シュ", romaji: "shu" },
      { kana: "ショ", romaji: "sho" },
      { kana: "チャ", romaji: "cha" },
      { kana: "チュ", romaji: "chu" },
      { kana: "チョ", romaji: "cho" },
      { kana: "ニャ", romaji: "nya" },
      { kana: "ニュ", romaji: "nyu" },
      { kana: "ニョ", romaji: "nyo" },
      { kana: "ヒャ", romaji: "hya" },
      { kana: "ヒュ", romaji: "hyu" },
      { kana: "ヒョ", romaji: "hyo" },
      { kana: "ミャ", romaji: "mya" },
      { kana: "ミュ", romaji: "myu" },
      { kana: "ミョ", romaji: "myo" },
      { kana: "リャ", romaji: "rya" },
      { kana: "リュ", romaji: "ryu" },
      { kana: "リョ", romaji: "ryo" },
      { kana: "ギャ", romaji: "gya" },
      { kana: "ギュ", romaji: "gyu" },
      { kana: "ギョ", romaji: "gyo" },
      { kana: "ジャ", romaji: "ja" },
      { kana: "ジュ", romaji: "ju" },
      { kana: "ジョ", romaji: "jo" },
      { kana: "ビャ", romaji: "bya" },
      { kana: "ビュ", romaji: "byu" },
      { kana: "ビョ", romaji: "byo" },
      { kana: "ピャ", romaji: "pya" },
      { kana: "ピュ", romaji: "pyu" },
      { kana: "ピョ", romaji: "pyo" },
    ],
  },
};

function buildRows(script: KanaScript): KanaRowDefinition[] {
  const basic = flatRowsByScript[script].basic;
  const dakuten = flatRowsByScript[script].dakuten;
  const combo = flatRowsByScript[script].combo;

  return [
    { key: "basic-a", group: "basic", label: "a · i · u · e · o", entries: sliceRow(basic, 0, 5) },
    { key: "basic-ka", group: "basic", label: "ka · ki · ku · ke · ko", entries: sliceRow(basic, 5, 5) },
    { key: "basic-sa", group: "basic", label: "sa · shi · su · se · so", entries: sliceRow(basic, 10, 5) },
    { key: "basic-ta", group: "basic", label: "ta · chi · tsu · te · to", entries: sliceRow(basic, 15, 5) },
    { key: "basic-na", group: "basic", label: "na · ni · nu · ne · no", entries: sliceRow(basic, 20, 5) },
    { key: "basic-ha", group: "basic", label: "ha · hi · fu · he · ho", entries: sliceRow(basic, 25, 5) },
    { key: "basic-ma", group: "basic", label: "ma · mi · mu · me · mo", entries: sliceRow(basic, 30, 5) },
    { key: "basic-ya", group: "basic", label: "ya · yu · yo", entries: sliceRow(basic, 35, 3) },
    { key: "basic-ra", group: "basic", label: "ra · ri · ru · re · ro", entries: sliceRow(basic, 38, 5) },
    { key: "basic-wa", group: "basic", label: "wa · wo · n", entries: sliceRow(basic, 43, 3) },
    { key: "dakuten-ga", group: "dakuten", label: "ga · gi · gu · ge · go", entries: sliceRow(dakuten, 0, 5) },
    { key: "dakuten-za", group: "dakuten", label: "za · ji · zu · ze · zo", entries: sliceRow(dakuten, 5, 5) },
    { key: "dakuten-da", group: "dakuten", label: "da · ji · zu · de · do", entries: sliceRow(dakuten, 10, 5) },
    { key: "dakuten-ba", group: "dakuten", label: "ba · bi · bu · be · bo", entries: sliceRow(dakuten, 15, 5) },
    { key: "dakuten-pa", group: "dakuten", label: "pa · pi · pu · pe · po", entries: sliceRow(dakuten, 20, 5) },
    { key: "combo-kya", group: "combo", label: "kya · kyu · kyo", entries: sliceRow(combo, 0, 3) },
    { key: "combo-sha", group: "combo", label: "sha · shu · sho", entries: sliceRow(combo, 3, 3) },
    { key: "combo-cha", group: "combo", label: "cha · chu · cho", entries: sliceRow(combo, 6, 3) },
    { key: "combo-nya", group: "combo", label: "nya · nyu · nyo", entries: sliceRow(combo, 9, 3) },
    { key: "combo-hya", group: "combo", label: "hya · hyu · hyo", entries: sliceRow(combo, 12, 3) },
    { key: "combo-mya", group: "combo", label: "mya · myu · myo", entries: sliceRow(combo, 15, 3) },
    { key: "combo-rya", group: "combo", label: "rya · ryu · ryo", entries: sliceRow(combo, 18, 3) },
    { key: "combo-gya", group: "combo", label: "gya · gyu · gyo", entries: sliceRow(combo, 21, 3) },
    { key: "combo-ja", group: "combo", label: "ja · ju · jo", entries: sliceRow(combo, 24, 3) },
    { key: "combo-bya", group: "combo", label: "bya · byu · byo", entries: sliceRow(combo, 27, 3) },
    { key: "combo-pya", group: "combo", label: "pya · pyu · pyo", entries: sliceRow(combo, 30, 3) },
  ];
}

export const kanaRowsByScript: Record<KanaScript, KanaRowDefinition[]> = {
  hiragana: buildRows("hiragana"),
  katakana: buildRows("katakana"),
};

export const kanaSelectionKeys: KanaSelectionKey[] = [
  "basic",
  "dakuten",
  "combo",
  ...kanaRowsByScript.hiragana.map((row) => row.key),
];

export function getKanaRows(script: KanaScript): KanaRowDefinition[] {
  return kanaRowsByScript[script];
}

export function getKanaEntries(script: KanaScript, selections: KanaSelectionKey[]): KanaEntry[] {
  const selected = new Set(selections);
  const rows = kanaRowsByScript[script];
  const output: KanaEntry[] = [];

  rows.forEach((row) => {
    if (selected.has(row.key) || selected.has(row.group)) {
      output.push(...row.entries);
    }
  });

  return output;
}
